"""Final-release analysis scaffolding for SciSci-CiteEvidence."""

from citeevidence.final_release.claims import ClaimRecord, EvidenceRecord
from citeevidence.final_release.figures import (
    plot_context_volume_vs_evidence_use_reversal,
    plot_critique_bottleneck_heatmap,
    plot_object_role_signature_map,
    plot_section_function_lift_heatmap,
)
from citeevidence.final_release.io import ensure_directory, maybe_read_csv, write_source_csv
from citeevidence.final_release.metrics import (
    add_shrunk_evidence_use_share,
    build_critique_bottleneck_matrix,
    build_critique_evidence_cards,
    build_object_role_signature,
    build_paper_evidence_use_table,
    build_ranking_reversal_plot_table,
    build_section_function_counts,
    build_section_function_lift,
    classify_critique_bottleneck_family,
    classify_object_role_quadrant,
    compute_ranking_reversal,
    filter_ranking_reversal_eligible,
    format_section_label,
)
from citeevidence.final_release.qa import (
    FORBIDDEN_CLAIMS,
    REQUIRED_CAVEATS,
    build_label_quality_summary,
    build_stratified_qa_sample,
    summarize_confidence_by_intent,
    summarize_failure_categories,
    validate_citation_context_volume_terms,
    validate_evidence_grounding,
    validate_forbidden_claims,
    validate_required_caveats,
)
from citeevidence.final_release.report import (
    build_final_release_figure_manifest,
    build_final_release_limitations,
    build_final_release_report,
    validate_final_release_report_text,
)
from citeevidence.final_release.runner import (
    DEFAULT_CONTEXTS_PATH,
    DEFAULT_EXCLUDED_LABELS_PATH,
    DEFAULT_FAILED_DIAGNOSTICS_PATH,
    DEFAULT_FINAL_RELEASE_EVIDENCE_CARDS,
    DEFAULT_FINAL_RELEASE_FIGURES_DIR,
    DEFAULT_FINAL_RELEASE_QA_SAMPLE,
    DEFAULT_FINAL_RELEASE_REPORT,
    DEFAULT_FINAL_RELEASE_SOURCE_DATA_DIR,
    DEFAULT_OBJECT_GRAPH_CANDIDATES_PATH,
    DEFAULT_OBJECT_MENTIONS_PATH,
    DEFAULT_PHASE1_PATH,
    DEFAULT_PHASE2_LABELS_PATH,
    build_final_release_object_edges,
    prepare_final_release_labels,
    run_final_release_analysis,
)

__all__ = [
    "ClaimRecord",
    "DEFAULT_CONTEXTS_PATH",
    "DEFAULT_EXCLUDED_LABELS_PATH",
    "DEFAULT_FAILED_DIAGNOSTICS_PATH",
    "DEFAULT_FINAL_RELEASE_EVIDENCE_CARDS",
    "DEFAULT_FINAL_RELEASE_FIGURES_DIR",
    "DEFAULT_FINAL_RELEASE_QA_SAMPLE",
    "DEFAULT_FINAL_RELEASE_REPORT",
    "DEFAULT_FINAL_RELEASE_SOURCE_DATA_DIR",
    "DEFAULT_OBJECT_GRAPH_CANDIDATES_PATH",
    "DEFAULT_OBJECT_MENTIONS_PATH",
    "DEFAULT_PHASE1_PATH",
    "DEFAULT_PHASE2_LABELS_PATH",
    "EvidenceRecord",
    "FORBIDDEN_CLAIMS",
    "REQUIRED_CAVEATS",
    "add_shrunk_evidence_use_share",
    "build_critique_bottleneck_matrix",
    "build_critique_evidence_cards",
    "build_final_release_figure_manifest",
    "build_final_release_limitations",
    "build_final_release_report",
    "build_label_quality_summary",
    "build_final_release_object_edges",
    "build_object_role_signature",
    "build_paper_evidence_use_table",
    "build_ranking_reversal_plot_table",
    "build_section_function_counts",
    "build_section_function_lift",
    "build_stratified_qa_sample",
    "classify_critique_bottleneck_family",
    "classify_object_role_quadrant",
    "compute_ranking_reversal",
    "ensure_directory",
    "filter_ranking_reversal_eligible",
    "format_section_label",
    "maybe_read_csv",
    "plot_context_volume_vs_evidence_use_reversal",
    "plot_critique_bottleneck_heatmap",
    "plot_object_role_signature_map",
    "plot_section_function_lift_heatmap",
    "prepare_final_release_labels",
    "run_final_release_analysis",
    "summarize_confidence_by_intent",
    "summarize_failure_categories",
    "validate_citation_context_volume_terms",
    "validate_evidence_grounding",
    "validate_final_release_report_text",
    "validate_forbidden_claims",
    "validate_required_caveats",
    "write_source_csv",
]
