"""Final-release analysis scaffolding for SciSci-CiteEvidence."""

from citeevidence.final_release.claims import ClaimRecord, EvidenceRecord
from citeevidence.final_release.figures import (
    plot_context_volume_vs_evidence_use_reversal,
    plot_critique_bottleneck_heatmap,
    plot_object_role_signature_map,
    plot_section_function_lift_heatmap,
)
from citeevidence.final_release.io import ensure_directory, maybe_read_csv, write_source_csv
from citeevidence.final_release.metrics import (
    add_shrunk_evidence_use_share,
    build_critique_bottleneck_matrix,
    build_critique_evidence_cards,
    build_object_role_signature,
    build_paper_evidence_use_table,
    build_ranking_reversal_plot_table,
    build_section_function_counts,
    build_section_function_lift,
    classify_critique_bottleneck_family,
    classify_object_role_quadrant,
    compute_ranking_reversal,
    filter_ranking_reversal_eligible,
    format_section_label,
)
from citeevidence.final_release.qa import (
    FORBIDDEN_CLAIMS,
    REQUIRED_CAVEATS,
    build_label_quality_summary,
    build_stratified_qa_sample,
    summarize_confidence_by_intent,
    summarize_failure_categories,
    validate_citation_context_volume_terms,
    validate_evidence_grounding,
    validate_forbidden_claims,
    validate_required_caveats,
)

__all__ = [
    "ClaimRecord",
    "EvidenceRecord",
    "FORBIDDEN_CLAIMS",
    "REQUIRED_CAVEATS",
    "add_shrunk_evidence_use_share",
    "build_critique_bottleneck_matrix",
    "build_critique_evidence_cards",
    "build_label_quality_summary",
    "build_object_role_signature",
    "build_paper_evidence_use_table",
    "build_ranking_reversal_plot_table",
    "build_section_function_counts",
    "build_section_function_lift",
    "build_stratified_qa_sample",
    "classify_critique_bottleneck_family",
    "classify_object_role_quadrant",
    "compute_ranking_reversal",
    "ensure_directory",
    "filter_ranking_reversal_eligible",
    "format_section_label",
    "maybe_read_csv",
    "plot_context_volume_vs_evidence_use_reversal",
    "plot_critique_bottleneck_heatmap",
    "plot_object_role_signature_map",
    "plot_section_function_lift_heatmap",
    "summarize_confidence_by_intent",
    "summarize_failure_categories",
    "validate_citation_context_volume_terms",
    "validate_evidence_grounding",
    "validate_forbidden_claims",
    "validate_required_caveats",
    "write_source_csv",
]
